apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloads.tekton.platform
spec:
  group: tekton.platform
  scope: Namespaced
  names:
    plural: workloads
    singular: workload
    kind: Workload
    shortNames:
      - wk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                build:
                  type: object
                  properties:
                    env:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                source:
                  type: object
                  properties:
                    git:
                      type: object
                      properties:
                        url:
                          type: string
                        ref:
                          type: object
                          properties:
                            branch:
                              type: string
                params:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                      - name
                      - value
              required:
                - params
            status:  # ⬅️ 여기에 status 필드 정의 추가
              type: object
              properties:
                lastAppliedRevision:
                  type: string
                lastCommitSHA:
                  type: string
                lastPipelineRunName:
                  type: string
                phase:
                  type: string
      subresources:
        status: {}
