---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-tekton-pipeline-policy
spec:
  generateExisting: true
  background: true
  rules:
    - name: generate-tekton-pipeline-rule
      match:
        resources:
          kinds: ["Workload"]
      generate:
        apiVersion: tekton.dev/v1
        kind: Pipeline
        name: master-ci-pipeline
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          apiVersion: tekton.dev/v1
          kind: Pipeline
          metadata:
            name: master-ci-pipeline
            namespace: "{{ request.object.metadata.namespace }}"
          spec:
            params:
              - name: buildServiceBindings
                type: string
                default: ""
              - name: cache_image_url
                type: string
                description: "URL for the build cache image"
                default: "harbor-infra.huntedhappy.kro.kr/library/build-cache:latest"
              - name: ci-git-revision
                type: string
                description: "The full Git commit SHA for the current build"
              - name: ci-git-branch
                type: string
              - name: ci-git-url
                type: string
              - name: ci-git-repo-path
                type: string
                default: ""
              - name: ci-git-project-name
                type: string
              - name: ci-skip-mr
                type: string
                default: "false"
              - name: gitops_server_address
                type: string
              - name: gitops_branch
                type: string
              - name: gitops_repository_name
                type: string
              - name: gitops_repository_owner
                type: string
              - name: gitops_user_email
                type: string
              - name: gitops_commit_message
                type: string
              - name: gitops_ssh_secret
                type: string
              - name: gitops_commit_branch
                type: string
              - name: gitops_server_kind
                type: string
                default: "gitlab"
              - name: gitops_pull_request_title
                type: string
                default: "ready for review"
              - name: gitops_pull_request_body
                type: string
                default: "generated by Tekton"
              - name: workloadname
                type: string
              - name: image_repo_address
                type: string
                description: "The image registry address (e.g., my-registry.io)"
              - name: image_repo_path
                type: string
                description: "The path or project within the registry (e.g., my-project)"
              - name: ingressclassname
                type: string
                default: ""
              - name: dockerfile
                type: string
                default: ""
              - name: submodules
                type: string
                default: "false"
              - name: domain
                type: string
              - name: clusterBuilder
                type: string
              - name: build_workspace_claim
                type: string
              - name: build_git_secret
                type: string
            workspaces:
              - name: shared-data
              - name: git-credentials
              - name: settings-xml
            tasks:
              - name: fetch-source
                taskRef:
                  name: git-clone
                  kind: Task
                params:
                  - name: url
                    value: '\$(params.ci-git-url)'
                  - name: revision
                    value: '\$(params.ci-git-revision)'
                  - name: submodules
                    value: '\$(params.submodules)'
                workspaces:
                  - name: output
                    workspace: shared-data

              - name: build-with-buildkit
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: in
                    values: ["./Dockerfile"]
                taskRef:
                  name: buildkit
                  kind: Task
                params:
                  - name: IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: CONTEXT
                    value: .
                  - name: DOCKERFILE
                    value: '\$(params.dockerfile)'
                  - name: EXTRA_ARGS
                    value:
                      - --skip-insecure-entitlement
                workspaces:
                  - name: source
                    workspace: shared-data

              - name: build-default-with-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ['\$(params.buildServiceBindings)']
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["default"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: gcr.io/buildpacks/builder:v1
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                  - name: ENV_VARS
                    value:
                      - BP_MAVEN_SETTINGS_PATH=/workspace/settings-xml/settings.xml
                      - BP_LOG_LEVEL=DEBUG
                workspaces:
                  - name: source
                    workspace: shared-data
                  - name: settings-xml
                    workspace: settings-xml

              - name: build-base-with-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ['\$(params.buildServiceBindings)']
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["base"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: paketobuildpacks/builder:base
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                  - name: ENV_VARS
                    value:
                      - BP_MAVEN_SETTINGS_PATH=/workspace/settings-xml/settings.xml
                      - BP_LOG_LEVEL=DEBUG
                workspaces:
                  - name: source
                    workspace: shared-data
                  - name: settings-xml
                    workspace: settings-xml

              - name: build-full-with-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ['\$(params.buildServiceBindings)']
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["full"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: paketobuildpacks/builder:full
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                  - name: ENV_VARS
                    value:
                      - BP_MAVEN_SETTINGS_PATH=/workspace/settings-xml/settings.xml
                      - BP_LOG_LEVEL=DEBUG
                workspaces:
                  - name: source
                    workspace: shared-data
                  - name: settings-xml
                    workspace: settings-xml

              - name: build-default-without-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ["false"]
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["default"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: gcr.io/buildpacks/builder:v1
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                workspaces:
                  - name: source
                    workspace: shared-data

              - name: build-base-without-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ["false"]
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["base"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: paketobuildpacks/builder:base
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                workspaces:
                  - name: source
                    workspace: shared-data

              - name: build-full-without-nexus-for-buildpacks
                runAfter:
                  - fetch-source
                when:
                  - input: '\$(params.dockerfile)'
                    operator: notin
                    values: ["./Dockerfile"]
                  - input: '\$(params.buildServiceBindings)'
                    operator: in
                    values: ["false"]
                  - input: '\$(params.clusterBuilder)'
                    operator: in
                    values: ["full"]
                taskRef:
                  name: buildpacks
                  kind: Task
                params:
                  - name: APP_IMAGE
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: BUILDER_IMAGE
                    value: paketobuildpacks/builder:full
                  - name: CACHE_IMAGE
                    value: '\$(params.cache_image_url)'
                workspaces:
                  - name: source
                    workspace: shared-data

              - name: generate-manifest
                runAfter:
                  - build-with-buildkit
                  - build-default-with-nexus-for-buildpacks
                  - build-base-with-nexus-for-buildpacks
                  - build-full-with-nexus-for-buildpacks
                  - build-default-without-nexus-for-buildpacks
                  - build-base-without-nexus-for-buildpacks
                  - build-full-without-nexus-for-buildpacks
                taskRef:
                  name: generate-manifest
                  kind: Task
                params:
                  - name: IMAGE_REPO
                    value: '\$(params.image_repo_address)/\$(params.image_repo_path)/\$(params.workloadname):\$(params.ci-git-revision)'
                  - name: CI_GIT_PROJECT_NAME
                    value: '\$(params.ci-git-project-name)'
                  - name: GITOPS_SERVER_ADDRESS
                    value: '\$(params.gitops_server_address)'
                  - name: GITOPS_BRANCH
                    value: '\$(params.gitops_branch)'
                  - name: GITOPS_COMMIT_BRANCH
                    value: '\$(params.gitops_commit_branch)'
                  - name: GITOPS_REPOSITORY_NAME
                    value: '\$(params.gitops_repository_name)'
                  - name: GITOPS_REPOSITORY_OWNER
                    value: '\$(params.gitops_repository_owner)'
                  - name: WORKLOADNAME
                    value: '\$(params.workloadname)'
                  - name: DOMAIN
                    value: '\$(params.domain)'
                  - name: INGRESSCLASSNAME
                    value: '\$(params.ingressclassname)'
                  - name: CI_SKIP_MR
                    value: '\$(params.ci-skip-mr)'
                  - name: GITOPS_SSH_SECRET
                    value: '\$(params.gitops_ssh_secret)'
                workspaces:
                  - name: source
                    workspace: shared-data
