apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-controller
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-controller
  template:
    metadata:
      labels:
        app: tekton-controller
    spec:
      serviceAccountName: controller-sa # 실제 사용하는 ServiceAccount 이름으로 변경
      containers:
      - name: tekton-controller
        image: harbor-infra.huntedhappy.kro.kr/library/tekton-controller:latest
        args: ["--leader-elect"]
        env:
        - name: GIT_SHA_CACHE_TTL_SECONDS
          value: "300"
        ports:
        - name: healthz
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
