
apiVersion: tekton.platform/v1alpha1
kind: Workload
metadata:
  annotations:
    tekton.platform/build_git_secret: git-credentials
    tekton.platform/build_workspace_claim: shared-data
  name: tanzu-java-web-app-dev
  namespace: dev
spec:
  params:
#    - name: buildServiceBindings
#      value: settings-xml
    - name: submodules
      value: "false"
#    - name: dockerfile
#      value: ./Dockerfile
    - name: gitops-skip-mr
      value: "true"
    - name: gitops_server_address
      value: https://gitlab.huntedhappy.kro.kr
    - name: gitops_commit_branch
      value: main
    - name: gitops_branch
      value: dev
    - name: gitops_repository_name
      value: tanzu-java-web-app-manifest
    - name: gitops_repository_owner
      value: tanzu
    - name: gitops_user_email
      value: my1208@openbase.co.kr
    - name: gitops_commit_message
      value: test_giops
    - name: gitops_ssh_secret
      value: git-credentials
    - name: gitops_server_kind
      value: gitlab      
    - name: gitops_pull_request_title
      value:  "ready for review"
    - name: gitops_pull_request_body
      value: "generated by Tekton"
    - name: image_repo_address
      value: harbor-infra.huntedhappy.kro.kr
    - name: image_repo_path
      value: custom
    - name: dockerconfig
      value: registry-creds
    - name: ingressclassname
      value: contour
    - name: domain
      value: huntedhappy.kro.kr
    - name: clusterBuilder
      value: default
    - name: serviceAccount
      value: pipeline
  build:
    env:
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
#      - BP_MAVEN_SETTINGS_PATH=/workspace/settings-xml/settings.xml
      - BP_LOG_LEVEL=DEBUG
  env:
    - TZ=Asia/Seoul
  resources:
    limits:
      cpu: 1Gi
      memory: 1Gi
    requests:
      cpu: "512Mi"
      memory: "512Mi"
  source:
    git:
      url: https://gitlab.huntedhappy.kro.kr/tanzu/tanzu-java-web-app.git
      ref:
        branch: main
